<?php

if (!function_exists('getCountryCodes')) {
    function getCountryCodes()
    {
        return [
            '+966' => 'Saudi Arabia',
            '+1' => 'United States',
            '+7' => 'Russia',
            '+20' => 'Egypt',
            '+27' => 'South Africa',
            '+30' => 'Greece',
            '+31' => 'Netherlands',
            '+32' => 'Belgium',
            '+33' => 'France',
            '+34' => 'Spain',
            '+36' => 'Hungary',
            '+39' => 'Italy',
            '+40' => 'Romania',
            '+41' => 'Switzerland',
            '+43' => 'Austria',
            '+44' => 'United Kingdom',
            '+45' => 'Denmark',
            '+46' => 'Sweden',
            '+48' => 'Poland',
            '+49' => 'Germany',
            '+51' => 'Peru',
            '+52' => 'Mexico',
            '+54' => 'Argentina',
            '+55' => 'Brazil',
            '+56' => 'Chile',
            '+57' => 'Colombia',
            '+58' => 'Venezuela',
            '+60' => 'Malaysia',
            '+61' => 'Australia',
            '+62' => 'Indonesia',
            '+63' => 'Philippines',
            '+64' => 'New Zealand',
            '+65' => 'Singapore',
            '+66' => 'Thailand',
            '+81' => 'Japan',
            '+82' => 'South Korea',
            '+84' => 'Vietnam',
            '+86' => 'China',
            '+90' => 'Turkey',
            '+91' => 'India',
            '+92' => 'Pakistan',
            '+93' => 'Afghanistan',
            '+94' => 'Sri Lanka',
            '+95' => 'Myanmar',
            '+98' => 'Iran',
            '+143' => 'Canada',
            '+212' => 'Morocco',
            '+216' => 'Tunisia',
            '+225' => 'Cote d\'Ivoire',
            '+234' => 'Nigeria',
            '+254' => 'Kenya',
            '+420' => 'Czech Republic',
            '+591' => 'Bolivia',
            '+673' => 'Brunei',
            '+678' => 'Vanuatu',
            '+679' => 'Fiji',
            '+682' => 'Cook Islands',
            '+683' => 'Niue',
            '+685' => 'Western Samoa',
            '+687' => 'American Samoa',
            '+688' => 'Nauru',
            '+689' => 'Kiribati',
            '+691' => 'Marshall Islands',
            '+692' => 'Micronesia (Federated States of)',
            '+694' => 'Palau',
            '+698' => 'Easter Island',
            '+850' => 'North Korea',
            '+852' => 'Hong Kong',
            '+853' => 'Macau',
            '+855' => 'Cambodia',
            '+886' => 'Taiwan',
            '+960' => 'Maldives',
            '+965' => 'Kuwait',
            '+967' => 'Yemen',
            '+968' => 'Oman',
            '+970' => 'Palestine',
            '+971' => 'United Arab Emirates',
            '+974' => 'Qatar',
            '+977' => 'Nepal',
            '+975' => 'Bhutan',
            '+976' => 'Mongolia',
            '+977' => 'Nepal',
            '+992' => 'Tajikistan',
            '+993' => 'Turkmenistan',
            '+994' => 'Azerbaijan',
            '+995' => 'Georgia',
            '+996' => 'Kyrgyzstan',
            '+998' => 'Uzbekistan',
        ];
    }
}









